# Generated by Django 5.2.2 on 2025-06-10 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_booking_user_alter_rating_user"),
        ("notifications", "0003_alter_notification_event_alter_notification_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_notifications",
                to="events.event",
            ),
        ),
    ]
